In [ ]:
"""
在Torch中张量以 "类" 的形式封装起来，对张量的一些运算、处理的方法被封装在类中，官方文档：
https://pytorch.org/docs/stable/torch.html#tensors
"""

import torch

# 使用torch.tensor()创建张量(常用)
tensor = torch.tensor([[1, 2], [3, 4]])
"""
torch.tensor(
    data: Any,                      # 输入数据(标量、序列(列表/元组)、多维数组、Numpy 数组、其他张量对象)
    dtype: dtype | None = None,     # 输出张量的数据类型(可选，不指定会自动判断)
    device: DeviceLikeType | None = None,  # 控制张量存储位置('cpu'|'cuda'|'cuda:0', 不指定会使用默认设备)
    requires_grad: bool = False,    # 是否启用梯度跟踪（Autograd 功能的核心开关）
    pin_memory: bool = False        # 是否锁定主机内存，加速 CPU→GPU 数据传输(仅当 device='cpu' 时有效)
) -> Tensor:    # 返回张量对象(新张量与原始对象完全独立)
"""

print(tensor)
print(tensor.device)

tensor([[1, 2],
        [3, 4]])
cpu


In [1]:
import torch

# 使用torch.Tensor()构造函数创建张量(不常用)
x = torch.Tensor([[1, 2], [3, 4]])
"""
class Tensor(
    *args: Any,                           # 输入数据
    device: DeviceLikeType | None = None  # 可选设备参数
)

注：
    这两个参数的传参与上面的 torch.tensor() 函数一样
    数据类型会被强制指定为 torch.float32 
"""

print(x)
print(x.dtype)

tensor([[1., 2.],
        [3., 4.]])
torch.float32


In [4]:
"""
如果需要创建指定类型和形状的张量（这些张量均未初始化，包含内存中的随机值）

还有诸如torch.IntTensor、torch.FloatTensor、torch.DoubleTensor、torch.LongTensor、torch.ShortTensor......等。
"""

import torch

tt1 = torch.IntTensor(2, 3)
print(tt1, tt1.dtype)
print('---------' * 10)

tt2 = torch.FloatTensor(3, 3)
print(tt2, tt2.dtype)
print('---------' * 10)

tt3 = torch.DoubleTensor(3, 3)
print(tt3, tt3.dtype)
print('---------' * 10)

tt4 = torch.LongTensor(3, 3)
print(tt4, tt4.dtype)
print('---------' * 10)

tt5 = torch.ShortTensor(3, 3)
print(tt5, tt5.dtype)



tensor([[377553376,      1481,         0],
        [        0,         0,         0]], dtype=torch.int32) torch.int32
------------------------------------------------------------------------------------------
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.float32
------------------------------------------------------------------------------------------
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64) torch.float64
------------------------------------------------------------------------------------------
tensor([[6361224316320,             0,             0],
        [            0,             0,             0],
        [            0,             0,             0]]) torch.int64
------------------------------------------------------------------------------------------
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16) torch.int16
