In [ ]:
"""
创建线性张量
"""

import torch

# 不用科学计数法打印
torch.set_printoptions(sci_mode=False)

# 1. 创建线性张量
r1 = torch.arange(0, 10, 2)
print(r1)

# 2. 在指定空间按照元素个数生成张量：等差
r2 = torch.linspace(3, 10, 10)
print(r2)

r2 = torch.linspace(3, 10000000, 10)
print(r2)
    

tensor([0, 2, 4, 6, 8])
tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])
tensor([    3.0000, 1111113.7500, 2222224.5000, 3333335.2500, 4444446.0000, 5555557.0000,
        6666668.0000, 7777778.5000, 8888889.0000, 10000000.0000])


In [ ]:
"""
创建随机张量
"""
import torch

# 1. 设置随机数种子
torch.manual_seed(123)

# 2. 获取随机数种子，需要查看种子时调用
print(torch.initial_seed())

# 3. 生成随机张量，均匀分布（范围 [0, 1)）
print(torch.rand(2, 3))

# 4. 生成随机张量：标准正态分布（均值 0，标准差 1）
print(torch.randn(2, 3))

# 5. 原生服从正态分布：均值为2， 方差为3，形状为1*4的正态分布
print(torch.normal(mean=2, std=3, size=(1, 4)))




123
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])
tensor([[ 0.9447,  0.6217, -1.3501],
        [-0.1881, -2.3891, -0.4759]])
tensor([[7.2808, 3.9642, 3.6471, 3.1014]])
