In [ ]:
"""
我们可以把单个元素tensor转换为Python数值，这是非常常用的操作
"""

import torch

# item(): 从单个元素的Tensor中获取标量值
# 获取元素和Tensor的维度没有关系，只要Tensor只有一个元素，都可以使用该方法取值
# 且仅适用于CPU张量
t1 = torch.tensor([1])
print(t1.item())

1


In [ ]:
"""
常见的加减乘除次方取反开方等各种操作，带有_的方法则会替换原始值。
"""

import torch

# 生成范围 [0, 10) 的 2x3 随机整数张量
data = torch.randint(0, 10, (2, 3))
print(data)

# 元素级别的加减乘除幂运算：不修改原始值，返回一个新的张量
print(data.add(1))
print(data.sub(1))
print(data.mul(2))
print(data.div(3))
print(data.pow(2))

# 元素级别的加减乘除幂运算：修改原始值
data = data.float()
data.add_(1)
data.sub_(1)
data.mul_(2)
data.div_(3.0)
data.pow_(2)
print(data)


tensor([[8, 7, 9],
        [6, 3, 0]])
tensor([[ 9,  8, 10],
        [ 7,  4,  1]])
tensor([[ 7,  6,  8],
        [ 5,  2, -1]])
tensor([[16, 14, 18],
        [12,  6,  0]])
tensor([[2.6667, 2.3333, 3.0000],
        [2.0000, 1.0000, 0.0000]])
tensor([[64, 49, 81],
        [36,  9,  0]])
tensor([[28.4444, 21.7778, 36.0000],
        [16.0000,  4.0000,  0.0000]])


In [4]:
"""
可以计算阿达玛积
阿达玛积是指两个形状相同的矩阵或张量对应位置的元素相乘。
"""
import torch

# 通过 * 直接计算两个形状相同的张量的阿达玛积
def test001():
    data1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    data2 = torch.tensor([[2, 3, 4], [2, 2, 3]])
    print(data1 * data2)

# 通过 mul()方法 计算两个形状相同的张量的阿达玛积
def test002():
    data1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    data2 = torch.tensor([[2, 3, 4], [2, 2, 3]])
    print(data1.mul(data2))


test001()
test002()


tensor([[ 2,  6, 12],
        [ 8, 10, 18]])
tensor([[ 2,  6, 12],
        [ 8, 10, 18]])


In [5]:
"""
Tensor可以实现矩阵乘法，但需要严格遵循矩阵乘法(点积)规则
    如果第一个矩阵的shape是 (N, M)，
    那么第二个矩阵 shape必须是 (M, P)，
    最后两个矩阵点积运算的shape为 (N, P)。
在 PyTorch 中，使用 @ 或者 matmul()方法 完成Tensor的乘法。
"""

import torch

data1 = torch.tensor([
    [1, 2, 3], 
    [4, 5, 6]
])
data2 = torch.tensor([
    [3, 2], 
    [2, 3], 
    [5, 3]
])

print(data1 @ data2)
print(data1.matmul(data2))




tensor([[22, 17],
        [52, 41]])
tensor([[22, 17],
        [52, 41]])
