从只含有单个元素的张量中获取其元素

In [ ]:
import torch

# item(): 从单个元素的Tensor中获取标量值
# 获取元素和Tensor的维度没有关系，只要Tensor只有一个元素，都可以使用该方法取值
t1 = torch.tensor([1], device='cpu')
print(t1.item())

1


In [ ]:
"""
可以通过运算符，直接对不同的张量进行计算
但是要注意张量形状需要相同，或者可以广播也行
运算的结果就是，对应位置的数字分别进行运算
"""

import torch

# 生成范围 [0, 10) 的 2x3 随机整数张量
data1 = torch.randint(0, 10, (2, 3))
data2 = torch.randint(0, 10, (2, 3))

# 加
data = data1 + data2
# 减
data = data1 - data2
# 乘
data = data1 * data2
# 除
data = data1 / data2
# 次方
data = data1 ** data2
# 取反
data = -data1
# 开方
data = data1.sqrt()




In [4]:
"""
可以计算阿达玛积
阿达玛积是指两个形状相同的矩阵或张量对应位置的元素相乘。
"""
import torch

# 通过 * 直接计算两个形状相同的张量的阿达玛积
def test001():
    data1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    data2 = torch.tensor([[2, 3, 4], [2, 2, 3]])
    print(data1 * data2)

# 通过 mul()方法 计算两个形状相同的张量的阿达玛积
def test002():
    data1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
    data2 = torch.tensor([[2, 3, 4], [2, 2, 3]])
    print(data1.mul(data2))


test001()
test002()


tensor([[ 2,  6, 12],
        [ 8, 10, 18]])
tensor([[ 2,  6, 12],
        [ 8, 10, 18]])


In [5]:
"""
Tensor可以实现矩阵乘法，但需要严格遵循矩阵乘法(点积)规则
    如果第一个矩阵的shape是 (N, M)，
    那么第二个矩阵 shape必须是 (M, P)，
    最后两个矩阵点积运算的shape为 (N, P)。
在 PyTorch 中，使用 @ 或者 matmul()方法 完成Tensor的乘法。
"""

import torch

data1 = torch.tensor([
    [1, 2, 3], 
    [4, 5, 6]
])
data2 = torch.tensor([
    [3, 2], 
    [2, 3], 
    [5, 3]
])

print(data1 @ data2)
print(data1.matmul(data2))




tensor([[22, 17],
        [52, 41]])
tensor([[22, 17],
        [52, 41]])
