In [2]:
"""
给定一个二维数组 arr = np.array([[1, 2, 3], [4, 5, 6]])，提取第 2 行的所有元素，并将其值加 10。
"""
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = arr[1]
arr1 += 10
print(arr)

[[ 1  2  3]
 [14 15 16]]


In [24]:
"""
给定一个二维数组 arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])，提取出所有大于3且小于8的元素，并将这些元素替换为-1。
"""
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
arr1[(3 < arr1) & (arr1 < 8)] = -1
print(arr1)

[[ 1  2  3]
 [-1 -1 -1]
 [-1  8  9]]


In [26]:
"""
3.给定一个二维数组 arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])，提取出主对角线上的元素，并将这些元素替换为它们的平方。
"""
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
size = arr.shape[0]
index = np.arange(size)
arr[index, index] = arr[index, index] ** 2
print(arr)

d = np.diag(arr) # 获取主对角线上的元素
print(d)

idx = np.diag_indices_from(arr) # 获取主对角线上的元素对应的下标（按维度给下标，与整数数组索引类似）
print(idx)

[[ 1  2  3]
 [ 4 25  6]
 [ 7  8 81]]
[ 1 25 81]
(array([0, 1, 2]), array([0, 1, 2]))


In [7]:
"""
4.给定一个二维数组 arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])，将其按行分割为两个子数组：第一个子数组包含前两行，第二个子数组包含最后一行。
"""
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = arr[:2]
arr2 = arr[2:]
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [22]:
"""
6.给定一个二维数组 arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])，找出所有大于5的元素的索引，并将这些元素替换为它们的平方根。
"""

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# arr[arr > 5] = np.sqrt(arr[arr > 5])
# print(arr)

idx = np.where(arr > 5) # 获取元素的索引下标，结果的数据格式按维度给出(与整数数组索引类似)
print(idx)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))
