In [1]:
"""
给定一个 NumPy 数组，编写一个函数，使用广播机制将数组的每个元素加上一个给定的标量值，并返回结果数组。
"""

import numpy as np
def add(ndarray):
    return ndarray + 1

arr = np.arange(10)
print(add(arr))

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
"""
创建一个二维 NumPy 数组，其中包含从 1 到 100 的整数，然后使用高级索引提取所有偶数，并计算这些偶数的总和。
"""

import numpy as np
arr = np.arange(1, 101).reshape(10,10)
bool_idx = arr % 2 == 0
print(arr[bool_idx])
print(sum(arr[bool_idx])) # 可以使用 np.sum() 函数算数值总和

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
2550


In [7]:
"""
编写一个函数，返回数组沿指定轴的方差。
"""
import numpy as np

def var(ndarray, axis=None):
    return np.var(ndarray, axis=axis)

arr = np.arange(10).reshape(2,5)
print(var(arr))
print(var(arr, 1))
print(var(arr, 0))
    

8.25
[2. 2.]
[6.25 6.25 6.25 6.25 6.25]


In [14]:
"""
实现一个函数，它接受一个 NumPy 数组，并返回该数组中所有唯一元素的列表。
"""
import numpy as np

def unique(ndarray):
    return np.unique(ndarray)

arr = np.array([[1, 2, 3, 4, 4],[4, 5, 6, 7, 7],[7, 8, 9, 10, 10]])
print(unique(arr))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [10]:
"""
使用Python的NumPy库，创建一个形状为(4,4)的二维数组，并且初始化所有元素为-1。
"""

import numpy as np
arr = np.full((4,4), -1)
print(arr)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [12]:
"""
假设数组：[1, 2, 3, 4, 3, 5, 3]，删除数组中所有值为3的元素。
"""
import numpy as np
arr = np.array([1, 2, 3, 4, 3, 5, 3])
bool_idx = arr == 3
arr = np.delete(arr, bool_idx)
print(arr)

[1 2 4 5]
